#!/bin/bash
# Delta scan at fixed N: one job per Delta.
#
# $P1 = N, $P2 = floor, $P3 = Delta.  p = 0.2 is set inside
# multilayer_optimizarion.py, and the LPDO files must already exist as
#     gapless_data/xxz/p0.2N${N}/M{1,2}_a0_XXnoise_p0.2N${N}_Delta${D}.h5
# (generated by:  julia xxz_init_data.jl 0.2 $N).
#
# Time limit is per job, i.e. per Delta. The recorded floor=1 runtimes from
# submit_all.sh are 5:01:45 at N=16 and 2:37:31 at N=12; those were measured on
# the uncompressed p=0.5 LPDOs, and the p=0.2 files are now truncated at
# lpdo_max_err=1e-8 (N=16 bond 508 -> 125), so these limits carry real headroom.
#
#   bash submit_delta_scan.sh          # N=16, floor=1, all 21 Delta
#   N=12 FLOOR=1 bash submit_delta_scan.sh
#   DELTAS="0.4 0.5 0.6" bash submit_delta_scan.sh

N=${N:-16}
FLOOR=${FLOOR:-1}
TIME=${TIME:-08:00:00}
DELTAS=${DELTAS:-"-1.0 -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1 0.0 \
0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0"}

# The job runs with sbatch's working directory, so multilayer_optimizarion.py and
# gapless_data/ must sit next to fidelity.slurm on the cluster. In this repo they
# live one level up instead, so accept either; DATA_DIR overrides both.
if [ -z "$DATA_DIR" ]; then
  if   [ -d "gapless_data/xxz" ];    then DATA_DIR="gapless_data"
  elif [ -d "../gapless_data/xxz" ]; then DATA_DIR="../gapless_data"
  else echo "ERROR: no gapless_data/xxz here or one level up; set DATA_DIR=" >&2; exit 1
  fi
fi
if [ ! -f "multilayer_optimizarion.py" ] && [ ! -f "../multilayer_optimizarion.py" ]; then
  echo "WARNING: multilayer_optimizarion.py is not next to fidelity.slurm --" >&2
  echo "         copy it (and gapless_data/) here before submitting." >&2
fi
echo "using DATA_DIR=$DATA_DIR"

n_sub=0
for D in $DELTAS; do
  f="${DATA_DIR}/xxz/p0.2N${N}/M1_a0_XXnoise_p0.2N${N}_Delta${D}.h5"
  if [ ! -f "$f" ]; then
    echo "SKIP  N=$N Delta=$D  (missing $f)"
    continue
  fi
  echo "Submitting N=$N floor=$FLOOR Delta=$D time=$TIME"
  sbatch --time="$TIME" \
         --job-name="fid_p02_N${N}_f${FLOOR}_D${D}" \
         --export=ALL,P1="$N",P2="$FLOOR",P3="$D" \
         fidelity.slurm
  n_sub=$((n_sub+1))
done
echo "submitted $n_sub job(s)"
